### ISSUE TITLE
Webpack build fails after upgrading to expose-loader 0.7.2

### ISSUE THREAD

**Issue by jimbolla** [webpack-contrib/expose-loader#31]
After running npm update, which upgraded expose-loader from 0.7.1 to 0.7.2, I now get the following errror:

```
ERROR in ./index.jsx
Module parse failed: C:\Projects\MIM\Code\MIM.Web\React\index.jsx Unexpected token (18:4)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (18:4)
    at Parser.pp$4.raise (C:\Projects\MIM\Code\MIM.Web\React\node_modules\webpack\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (C:\Projects\MIM\Code\MIM.Web\React\node_modules\webpack\node_modules\acorn\dist\acorn.js:603:10)
    at Parser.pp$3.parseExprAtom (C:\Projects\MIM\Code\MIM.Web\React\node_modules\webpack\node_modules\acorn\dist\acorn.js:1822:12)
    at Parser.pp$3.parseExprSubscripts (C:\Projects\MIM\Code\MIM.Web\React\node_modules\webpack\node_modules\acorn\dist\acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (C:\Projects\MIM\Code\MIM.Web\React\node_modules\webpack\node_modules\acorn\dist\acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (C:\Projects\MIM\Code\MIM.Web\React\node_modules\webpack\node_modules\acorn\dist\acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (C:\Projects\MIM\Code\MIM.Web\React\node_modules\webpack\node_modules\acorn\dist\acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (C:\Projects\MIM\Code\MIM.Web\React\node_modules\webpack\node_modules\acorn\dist\acorn.js:1597:21)
    at Parser.pp$3.parseParenAndDistinguishExpression (C:\Projects\MIM\Code\MIM.Web\React\node_modules\webpack\node_modules\acorn\dist\acorn.js:1861:32)
    at Parser.pp$3.parseExprAtom (C:\Projects\MIM\Code\MIM.Web\React\node_modules\webpack\node_modules\acorn\dist\acorn.js:1796:19)
    at Parser.pp$3.parseExprSubscripts (C:\Projects\MIM\Code\MIM.Web\React\node_modules\webpack\node_modules\acorn\dist\acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (C:\Projects\MIM\Code\MIM.Web\React\node_modules\webpack\node_modules\acorn\dist\acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (C:\Projects\MIM\Code\MIM.Web\React\node_modules\webpack\node_modules\acorn\dist\acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (C:\Projects\MIM\Code\MIM.Web\React\node_modules\webpack\node_modules\acorn\dist\acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (C:\Projects\MIM\Code\MIM.Web\React\node_modules\webpack\node_modules\acorn\dist\acorn.js:1597:21)
    at Parser.pp$1.parseVar (C:\Projects\MIM\Code\MIM.Web\React\node_modules\webpack\node_modules\acorn\dist\acorn.js:1034:28)
    at Parser.pp$1.parseVarStatement (C:\Projects\MIM\Code\MIM.Web\React\node_modules\webpack\node_modules\acorn\dist\acorn.js:917:10)
    at Parser.pp$1.parseStatement (C:\Projects\MIM\Code\MIM.Web\React\node_modules\webpack\node_modules\acorn\dist\acorn.js:706:19)
    at Parser.pp$1.parseBlock (C:\Projects\MIM\Code\MIM.Web\React\node_modules\webpack\node_modules\acorn\dist\acorn.js:981:25)
    at Parser.pp$3.parseFunctionBody (C:\Projects\MIM\Code\MIM.Web\React\node_modules\webpack\node_modules\acorn\dist\acorn.js:2105:24)
    at Parser.pp$1.parseFunction (C:\Projects\MIM\Code\MIM.Web\React\node_modules\webpack\node_modules\acorn\dist\acorn.js:1065:10)
    at Parser.pp$1.parseFunctionStatement (C:\Projects\MIM\Code\MIM.Web\React\node_modules\webpack\node_modules\acorn\dist\acorn.js:818:17)
    at Parser.pp$1.parseStatement (C:\Projects\MIM\Code\MIM.Web\React\node_modules\webpack\node_modules\acorn\dist\acorn.js:694:19)
    at Parser.pp$1.parseTopLevel (C:\Projects\MIM\Code\MIM.Web\React\node_modules\webpack\node_modules\acorn\dist\acorn.js:638:25)
    at Parser.parse (C:\Projects\MIM\Code\MIM.Web\React\node_modules\webpack\node_modules\acorn\dist\acorn.js:516:17)
    at Object.parse (C:\Projects\MIM\Code\MIM.Web\React\node_modules\webpack\node_modules\acorn\dist\acorn.js:3098:39)
    at Parser.parse (C:\Projects\MIM\Code\MIM.Web\React\node_modules\webpack\lib\Parser.js:902:15)
    at DependenciesBlock.<anonymous> (C:\Projects\MIM\Code\MIM.Web\React\node_modules\webpack\lib\NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (C:\Projects\MIM\Code\MIM.Web\React\node_modules\webpack-core\lib\NormalModuleMixin.js:310:10)
    at nextLoader (C:\Projects\MIM\Code\MIM.Web\React\node_modules\webpack-core\lib\NormalModuleMixin.js:275:25)
 @ ./~/expose-loader?mim!./index.jsx 1:33-58
Child extract-text-webpack-plugin:
        + 7 hidden modules
```

It looks like the change is causing webpack to not pass my file through babel. If I downgrade back to 0.7.1, it starts working as expected. The relevant parts of my webpack.config.js:

```
module.exports = {
  context: __dirname,

  entry: {
    'app.js': [
      'set-webpack-public-path!',
      'bootstrap-loader',
      'font-awesome-webpack',
      'babel-polyfill',
      'fetch-ie8',

      'expose?mim!./index',
    ],
  },

  module: {
    loaders: [
      {
        test: /\.(jsx|js)$/,
        exclude: /node_modules/,
        loader: 'babel-loader?cacheDirectory',
      },
      //...
    ],
  },

  resolve: {
    extensions: ['', '.js', '.jsx'],
  },
};
```

**Comment by d3viant0ne** [comment]
Consolidating conversation to #29
